import {
  Calendar,
  User,
  Bell,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Upload,
  Download,
  Share,
  Heart,
  Star,
  Phone,
  Mail,
  Globe,
  Camera,
  ImageIcon,
  File,
  Paperclip,
  Send,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Filter,
  SortAsc,
  SortDesc,
  RefreshCw,
  LogOut,
  LogIn,
  UserPlus,
  UserMinus,
  Shield,
  Lock,
  Unlock,
  Key,
  Zap,
  Award,
  Target,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Bookmark,
  Tag,
  Flag,
  Clock3,
  CalendarIcon,
  LocateIcon as LocationIcon,
  UsersIcon,
  MessageCircleIcon as MessageIcon,
  SettingsIcon,
  HomeIcon,
  StarIcon as StudyIcon,
  TimerIcon as TaskIcon,
  AnchorIcon as AnnouncementIcon,
  HourglassIcon as HoursIcon,
} from "lucide-react"

export const Icons = {
  // Navigation
  home: HomeIcon,
  calendar: CalendarIcon,
  users: UsersIcon,
  messages: MessageIcon,
  hours: HoursIcon,
  study: StudyIcon,
  tasks: TaskIcon,
  announcements: AnnouncementIcon,
  settings: SettingsIcon,

  // General UI
  menu: Menu,
  search: Search,
  bell: Bell,
  user: User,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  upload: Upload,
  download: Download,
  share: Share,
  heart: Heart,
  star: Star,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,

  // Navigation arrows
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,

  // Actions
  x: X,
  check: Check,
  refresh: RefreshCw,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,

  // Status
  alertCircle: AlertCircle,
  info: Info,
  helpCircle: HelpCircle,

  // Auth
  logOut: LogOut,
  logIn: LogIn,
  userPlus: UserPlus,
  userMinus: UserMinus,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  key: Key,

  // Content
  camera: Camera,
  image: ImageIcon,
  file: File,
  paperclip: Paperclip,
  send: Send,

  // Location & Contact
  mapPin: LocationIcon,
  phone: Phone,
  mail: Mail,
  globe: Globe,

  // Analytics
  zap: Zap,
  award: Award,
  target: Target,
  trendingUp: TrendingUp,
  barChart: BarChart3,
  pieChart: PieChart,
  activity: Activity,

  // Time
  clock: Clock3,
  calendar: Calendar,
}

export type IconName = keyof typeof Icons
